<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEE36Z9j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEE36Z9j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEE36Z9j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEE36Z9j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEE36Z9j\App_KernelDevDebugContainer([
    'container.build_hash' => 'EE36Z9j',
    'container.build_id' => 'fb9c4292',
    'container.build_time' => 1579618061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEE36Z9j');
